/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import JDBC.JDBC;
import static JDBC.JDBC.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import lib.DataValidator;
import lib.MsgBox;
import model.NhanVienModel;
import Dao.NhanVienDao;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ArrayList<NhanVienModel> list = new ArrayList<>();
    int current = -1;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        btnPre = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLastt = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        rdoNam = new javax.swing.JRadioButton();
        txtMa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bttnSave = new javax.swing.JButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextArea();
        txtHoten = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        txtEmaill = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnFistAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Giới Tính: ");

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Rewind-icon.png"))); // NOI18N
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa Chỉ: ");

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Forward-icon.png"))); // NOI18N
        btnNext.setToolTipText("");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý User ");

        btnLastt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Last-icon.png"))); // NOI18N
        btnLastt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLasttActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-New-icon.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        jLabel2.setText("Mã Sv: ");

        bttnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-icon.png"))); // NOI18N
        bttnSave.setText("Save");
        bttnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        jLabel3.setText("Họ Tên: ");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtDiachi.setColumns(20);
        txtDiachi.setRows(5);
        jScrollPane1.setViewportView(txtDiachi);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Email: ");

        jLabel5.setText("Số Đt: ");

        btnFistAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-First-icon.png"))); // NOI18N
        btnFistAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFistActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoten)
                                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(txtEmaill)
                                    .addComponent(txtSdt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFistAction, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLastt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bttnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmaill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(bttnSave)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPre)
                    .addComponent(btnNext)
                    .addComponent(btnLastt)
                    .addComponent(btnFistAction))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	public void loadDataTable() {

//		ArrayList<NhanVienModel> list = NhanVienDao.getInstance().selectAll();
//		DefaultTableModel model_table = (DefaultTableModel) ta;
//		model_table.setRowCount(0);
//		for (NhanVienModel sinhVienModel : list) {
//			model_table.addRow(new Object[] { sinhVienModel.getMaSv(), sinhVienModel.getHoTen(),
//					sinhVienModel.getEmail(), sinhVienModel.getSoDT(), sinhVienModel.isGioiTinh() ? "Nam" : "Nữ",
//					sinhVienModel.getDiaChi() });
//		}
        try {
            try (Connection con = getConnection()) {
                Statement st = con.createStatement();
                String Query = "select * from SinhVien";
                ResultSet rs = st.executeQuery(Query);
                list.clear();
                while (rs.next()) {
                    String maSv = rs.getString(1);
                    String Ten = rs.getString(2);
                    String Email = rs.getString(3);
                    String sodt = rs.getString(4);
                    boolean gt = rs.getBoolean(5);
                    String diaChi = rs.getString(6);
//                    Student sv = new Student(maSv, Ten, Email, sodt, diaChi, gt);
                    NhanVienModel sv = new NhanVienModel(maSv, Ten, Email, sodt, gt, diaChi);
                    list.add(sv);
                }
                st.close();
                rs.close();
                System.out.println(con);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void New() {
        txtMa.setText("");
        txtHoten.setText("");
        txtSdt.setText("");
        txtEmaill.setText("");
        txtDiachi.setText("");
        buttonGroup1.clearSelection();

    }

    public void Display(int i) {
        NhanVienModel sv = list.get(i);
        txtMa.setText(sv.getMaSv());
        txtEmaill.setText(sv.getHoTen());
        txtSdt.setText(sv.getSoDT());
        txtHoten.setText(sv.getEmail());
        txtDiachi.setText(sv.getDiaChi());
        boolean gt = sv.isGioiTinh();
        if (gt == true) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
    }

    public void displayFormCapNhat() {
        NhanVienModel sv = getValueForm();
        txtMa.setText(sv.getMaSv());
        txtHoten.setText(sv.getHoTen());
        txtSdt.setText(sv.getSoDT());
        txtEmaill.setText(sv.getEmail());
        txtDiachi.setText(sv.getDiaChi());
        if (sv.isGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }

//		int i_row = table.getSelectedRow();
//		count = i_row;
    }

    public NhanVienModel getValueForm() {

//		int i_row = txtMa.getText();
//		String maSV = model_table.getValueAt(i_row, 0) + "";
        NhanVienModel s = new NhanVienModel();
//		s.setMaSv(maSV);
//
        NhanVienModel sv = NhanVienDao.getInstance().selectByID(s);
        return sv;
    }

    public void delete() {
        NhanVienModel s = getValueForm();

        int c = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa", "Notificaiton", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.NO_OPTION) {
            return;
        }
        if (NhanVienDao.getInstance().delete(s) > 1) {
            MsgBox.showMessageDialog(this, "Delete success", "Nottification");
        }
//        else {
//            MsgBox.showMessageDialog(this, "Delete success", "Nottification");
//        }

    }

    public void inserTableSV() {
        StringBuilder sb = new StringBuilder();
        DataValidator.validateIsID(txtMa, sb, "Mã sinh viên null");
        DataValidator.validateIsHoTen(txtHoten, sb, "Họ tên null");
        DataValidator.validateIsEmail(txtEmaill, sb, "Email null");
        DataValidator.validateIsSDT(txtSdt, sb, "Số ĐT null");
        DataValidator.validateChecked(buttonGroup1, sb, "Chưa chọn giới tính");
        if (sb.length() > 0) {
            MsgBox.showErrorDialog(this, sb.toString(), "Notificaiton");
            return;
        }
        String maSV = txtMa.getText();
        String hoTen = txtHoten.getText();
        String email = txtEmaill.getText();
        String soDT = txtSdt.getText();
        boolean gioiTinh = true;
        if (rdoNam.isSelected()) {
            gioiTinh = true;
        } else {
            gioiTinh = false;
        }
        String diaChi = txtDiachi.getText();
        NhanVienModel sv = new NhanVienModel(maSV, hoTen, email, soDT, gioiTinh, diaChi);
        if (NhanVienDao.getInstance().selectByID(sv) != null) {
            if (MsgBox.showConfirmDialog(this, "Bạn muốn cập nhật", "Notificaiton") == JOptionPane.NO_OPTION) {
                return;
            }
            if (NhanVienDao.getInstance().update(sv) > 0) {
                MsgBox.showMessageDialog(this, "Update success", "Notificaiton");
            } else {
                MsgBox.showMessageDialog(this, "Update fail", "Notificaiton");
            }
        } else {
            if (NhanVienDao.getInstance().insert(sv) > 0) {
                MsgBox.showMessageDialog(this, "Insert success", "Notificaiton");
            } else {
                MsgBox.showMessageDialog(this, "Insert success", "Notificaiton");
            }
        }
        loadDataTable();
    }

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        current--;
        if (current < 0) {
            JOptionPane.showMessageDialog(null, "Đang ở đầu danh sách!!!");
            return;
        }

        Display(current);
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        current++;
        if (current >= list.size()) {
            JOptionPane.showMessageDialog(null, "Đang ở cuối danh sách!!!");
            return;
        }
        Display(current);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLasttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLasttActionPerformed
        current = list.size() - 1;
        Display(current);
    }//GEN-LAST:event_btnLasttActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        New();
    }//GEN-LAST:event_btnAddActionPerformed

    private void bttnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSaveActionPerformed
        inserTableSV();
    }//GEN-LAST:event_bttnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        if (JOptionPane.showConfirmDialog(this, "Bạn Chắc Chắn Muốn Xóa Users Này", "??", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
//            return;
//        }
        delete();
//        New();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        displayFormCapNhat();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFistActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFistActionActionPerformed
        current = 0;
        Display(current);
    }//GEN-LAST:event_btnFistActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFistAction;
    private javax.swing.JButton btnLastt;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton bttnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextArea txtDiachi;
    private javax.swing.JTextField txtEmaill;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables

}
